<?php
/**
 * Gallery page — public demo gallery.
 */
$pageTitle = 'Demo Gallery — VoxelSwarm';
?>
<div style="width:100%; max-width:960px;">

  <div style="text-align:center; margin-bottom:40px;">
    <div class="sw-logo" style="justify-content:center; margin-bottom:16px;">
      <svg class="sw-logo-icon" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path class="voxel-top" d="M12 3L20 7.5L12 12L4 7.5Z" />
        <path class="voxel-left" d="M4 7.5L12 12L12 21L4 16.5Z" />
        <path class="voxel-right" d="M20 7.5L12 12L12 21L20 16.5Z" />
      </svg>
      <span class="sw-logo-text">VoxelSwarm</span>
    </div>
    <h1 class="sw-heading" style="font-size:28px;">Demo Gallery</h1>
    <p class="sw-subheading">Sites built with VoxelSite — each generated by AI in seconds.</p>
  </div>

  <?php if (empty($instances)): ?>
    <div class="sw-card" style="text-align:center; max-width:100%;">
      <p style="color:var(--sw-text-muted);">No demos yet. Check back soon.</p>
    </div>
  <?php else: ?>
    <div style="display:grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap:20px;">
      <?php foreach ($instances as $inst): ?>
        <a href="https://<?= htmlspecialchars($inst['subdomain']) ?>"
           target="_blank"
           style="display:block; text-decoration:none; color:inherit;"
           class="sw-card" style="max-width:100%; padding:0; overflow:hidden;">
          <?php
            $thumbPath = SWARM_STORAGE . '/gallery/' . $inst['slug'] . '.jpg';
            if (file_exists($thumbPath)):
          ?>
            <div style="aspect-ratio:16/10; overflow:hidden;">
              <img src="/storage/gallery/<?= htmlspecialchars($inst['slug']) ?>.jpg"
                   alt="<?= htmlspecialchars($inst['name']) ?>"
                   style="width:100%; height:100%; object-fit:cover; transition:transform 0.3s;"
                   onmouseover="this.style.transform='scale(1.03)'"
                   onmouseout="this.style.transform='scale(1)'">
            </div>
          <?php else: ?>
            <div style="aspect-ratio:16/10; background:var(--sw-bg); display:flex; align-items:center; justify-content:center;">
              <svg width="32" height="32" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:var(--sw-text-muted);">
                <path class="voxel-top" d="M12 3L20 7.5L12 12L4 7.5Z" />
                <path class="voxel-left" d="M4 7.5L12 12L12 21L4 16.5Z" />
                <path class="voxel-right" d="M20 7.5L12 12L12 21L20 16.5Z" />
              </svg>
            </div>
          <?php endif; ?>
          <div style="padding:16px 20px;">
            <div style="font-weight:600; font-size:15px; margin-bottom:4px;"><?= htmlspecialchars($inst['name']) ?></div>
            <div style="font-size:13px; color:var(--sw-accent);">View Demo →</div>
          </div>
        </a>
      <?php endforeach; ?>
    </div>
  <?php endif; ?>

</div>
